// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spnxfbfqqamdlvugbuwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwbnhmYmZxcWFtZGx2dWdidXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDgxNjMsImV4cCI6MjA1OTg4NDE2M30.bk_U__1vDa75AyRbv4IMchY5T1AO-xdl5z0JfWs1BdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);